playlist:
  name: Recommendations
  prune: yes
suggestion_types:
  - show
  - movie
weighting:
  stars:
    default: 5.0
    include: yes
  embeddings:
    model_name: "jinaai/jina-embeddings-v2-small-en"
server:
  host: 127.0.0.1
  port: 32401
recommendation:
  interval:
