playlist:
  name: Recommendations
  prune: yes
suggestion_types:
  - show
  - movie
weighting:
  stars:
    default: 2.5
    include: yes
  embeddings:
    model_name: "mixedbread-ai/mxbai-embed-large-v1"
  added: 0.01
  ratings:
    critic: 0 # 0.1e-1
    audience: 0 # 0.1e-1
    default: 5.0
server:
  host: 127.0.0.1
  port: 32401
recommendation:
  interval:
cache: 0x0D0E0200020704
